### ISSUE TITLE
Seal a dat to prevent further writes

### ISSUE THREAD

**Issue by millette** [datprotocol/discussions#7]
Since dats can grow to be quite large with a great number of files, I am wondering if an owner could mark a dat as read-only.

This would signal it won't be updated anymore or that further updates will happen on a new dat by specifying its key either in the current dat metadata or in its dat.json file.

**Comment by scriptjs** [comment]
Hi. A dat is implicitly read-only. You need to be the owner to be the writer. Sounds like you want some form of metadata to indicate no further updates will occur to freeze the data.

**Comment by millette** [comment]
@scriptjs Yes, for the owner. Read my proposition again :-)

**Comment by millette** [comment]
In other words, the owner wouldn't be able to update it, and readers would know there's nothing new to expect in this dat, and optionnally, see new dat for further updates.

**Comment by scriptjs** [comment]
kk. I agree that would be useful. I also create some data sets I'd like to be immutable after they are generated.

**Comment by millette** [comment]
I don't remember the details, but I think a dat can be created to be immutable. Only clue I found so far is <https://github.com/mafintosh/hypercore/issues/120>

**Comment by scriptjs** [comment]
A method to make feed.writable = false along with a metadata property indicating it it is sealed, whatever you want to call it, ought to do it.

**Comment by karissa** [comment]
You could put it in the readme or create a property in the dat.json

**Comment by millette** [comment]
It could be as simple as adding a ```followUpKey``` key to dat.json (false would indicate it is sealed but there is no follow up).

It would be pretty useful if dat (and protocol beneath) would stop reading a dat (for updates) or let the owner writeto it once it saw ```followUpKey``` in dat.json.

**Comment by bnewbold** [comment]
Encoding this feature/use-case in the protocol itself feels convoluted to me. I would vote to keep the protocol simpler (as-is) rather than add a new flag. It also puts a burden on every piece of client software to check this flag, expose the behavior to users in the user interface and documentation, etc. Eg, something like hashbase.io would need to indicate for every dat archive whether it was "live" or "frozen", and every user of hashbase would need to be educated about what that meant.

One alternative I would propose is for applications and users to refer to a dat archive by version (using the new "+" syntax to specify version in the `dat://` string); this would have the same degree of immutability that seems to be desired here. Would need to understand specific motivating use cases better to know if that would be good enough though.

Another pattern, which is what ScienceFair uses, is to have an index dat which contains references to sub-dats which contain actual files and data; this allows arbitrary scaling. The index dat could contain references to specific versions of sub-dats.

As an aside, i'd also point out that even if "frozen", referring to a dat archive by key isn't really the same as, eg, referring to the hash of a file or tip of a merkel tree. A malicious publisher (who controls the secret key) could potentially publish a fork of their hyperregister/hyperdrive with any "freeze" bit removed with new data; peers in the network would notice the divergence, but only if each locally had a copy of the previous-most-recent `tree` metadata (note: not even the full metadata register of a hyperdrive is sufficient!), or had a way to always check in with a distributed consensus instead of just trusting signatures. Eg, the trust model is sort of the same as certificate revocations in SSL and many other distributed systems: breaking trust and norms (eg, re-writing dat history) is *detectable* in an obvious public way, but only if the community is actively *looking* for it.

**Comment by millette** [comment]
The aside is really the crux of the matter. Since we can't actually freeze it 100% (the owner *could* revert the freeze bit by forking back in time), I'm going to close this issue.

Also, I agree it would complexify matters for everyone.

Thanks everyone for chiming in.
